import { useEffect } from 'react';
import Head from 'next/head'
import Vedio from './Vedio';

export default function About() {
      return (
        <div>
        <div className="container w-[300px] h-[200px]  mt-[20px] mx-auto p-4">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className="flex justify-center items-center gap-8">
            <div className="text-center">
              <h1 className="text-4xl font-bold mb-2">15K</h1>
              <p className="text-gray-600">Happy Customers</p>
            </div>
            <div className="text-center">
              <h1 className="text-4xl font-bold mb-2">150K</h1>
              <p className="text-gray-600">Monthly Visitors</p>
            </div>
            <div className="text-center">
              <h1 className="text-4xl font-bold mb-2">15</h1>
              <p className="text-gray-600">Countries Worldwide</p>
            </div>
            <div className="text-center">
              <h1 className="text-4xl font-bold mb-2">100+</h1>
              <p className="text-gray-600">Top Partners</p>
            </div>
          </main>
        </div>
        <Vedio/>
<div>
</div>
</div>
        
      )
    }
    


